### ISSUE TITLE
add message_thread_id

### ISSUE THREAD

**Issue by Gizex** [cslant/telegram-git-notifier-app#98]
pls add support for telegram topics, Need add message_thread_id

**Comment by tanhongit** [comment]
Hi @Gizex 

Thank you for your request. 
This is a necessary and useful requirement for premium accounts.

I will develop it but it may be released a bit slowly (about 2 or 3 new versions) because now I need to move the logic to a separate package to be transparent and easy to maintain for the community.

Hope you can wait for it, thanks a bunch!

**Comment by tanhongit** [comment]
Hello @Gizex, 

This feature is now available in the latest version ([v1.2.0](https://github.com/lbiltech/telegram-git-notifier-app/releases/tag/v1.2.0))

You can check the configuration to add topics for your supergroups through the env variable: **TELEGRAM_NOTIFY_CHAT_IDS**

In addition, other environment variables also have some changes. So, please look at the [readme.md](https://github.com/lbiltech/telegram-git-notifier-app/tree/v1.2.0?tab=readme-ov-file#iii-add-chat-ids-you-want-to-receive-notifications-to-the-env-file)

I hope it helps you now. If it really solves your problem. Please close the issue.
Thanks!

**Comment by tanhongit** [comment]
This Issue will be closed because there has been no response for a long time.
